Set realtime priority
jd/sysrqd pull request #4
Opened 2019-09-10 17:24 UTC by dagelf

2019-09-11 08:17 UTC, jd requested changes
That could be 2 different PR but that's fine :)

2019-09-11 08:17 UTC, jd commented on Makefile
> +	rm -f /etc/$(BIN).*
I'd prefer to list the files here to be on the safe side.

2019-09-11 08:17 UTC, jd commented on sysrqd.c
> +  exit(EXIT_FAILURE);
indentation?
also, is it really worth exiting? It can work without that.

2019-09-11 08:17 UTC, jd commented on sysrqd.secret
> +hello
We should not ship that. That's too dangerous.

2025-06-09 13:35 UTC, dagelf commented
I've updated the installation script to generate a random password. Perhaps we can note that this isn't supposed to be exposed to the internet... but I think anyone who knows to look for this, understands that. 

Would be trivial to add rate limits, or other commands.

2026-03-11 12:54 UTC, jd commented
I'll close this, not because it's bad, but because we should split this in different PR for different part. If you feel for it go ahead though, but this has been opened for too long.

2026-03-11 12:54 UTC, closed without merging